### ISSUE TITLE
Implement filters.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#1]

**Comment by samussiah** [comment]
Test notes:

- Filters appear in controls section when specified.
- Altering filter dropdown results in fewer lines displayed in multiples.
- Altering filter dropdown results in fewer records/pages displayed in listing.

Specify filters like so:

`{"filters": ["SITEID", "SEX", "ARM"]}`

**Comment by mhickle** [comment]
Pass
![1](https://user-images.githubusercontent.com/31038805/29835756-f2f022fa-8cc0-11e7-9cb1-6f2f11653cfd.PNG)
