### ISSUE TITLE
Improve chart toggle tooltip behavior.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#10]

**Comment by samussiah** [comment]
Test notes:

- _Measures_ checkbox displays _Remove all charts_ when checked.
- _Measures_ checkbox removes all charts when user un-checks checkbox.
- _Measures_ checkbox displays _Display all charts_ when un-checked.
- _Measures_ checkbox displays all charts when user checks checkbox.
- Individual measure checkboxes display _Remove chart_ when checked.
- Individual measure checkboxes remove corresponding chart when user un-checks checkbox.
- Individual measure checkboxes display _Display chart_ when un-checked.
- Individual measure checkboxes display corresponding chart when user checks checkbox.

**Comment by mhickle** [comment]
Pass
![10part1](https://user-images.githubusercontent.com/31038805/29834848-04190b8a-8cbe-11e7-90b5-73579cce23d6.PNG)
![10part2](https://user-images.githubusercontent.com/31038805/29834852-05d68d30-8cbe-11e7-92d3-06971dcde780.PNG)
