### ISSUE TITLE
paneled-outlier-explorer doesn't render in CAT using webcharts v1.10.0

### ISSUE THREAD

**Issue by dschwentker** [RhoInc/paneled-outlier-explorer#105]
When trying to load paneled-outlier-explorer in the CAT using Webcharts Version v1.10.0-dev, the chart is not rendering at all. The Controls panel loads, but not the Charts or Listing.

The error displayed at the top of the CAT is:
There might've been some problems initializing the chart. Errors include:
TypeError: d[0] is undefined

![image](https://user-images.githubusercontent.com/17090469/36493821-7b6725b2-16fe-11e8-92b4-89333608d034.png)

**Comment by jwildfire** [comment]
Closing this since we're all good in CAT with the latest builds of this library and webcharts.

@dschwentker @samussiah feel free to re-open if I'm missing something.
