### ISSUE TITLE
figure out how to deal with special characters

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#24]
they are fairly common in units in our sample data

<img width="185" alt="screen shot 2017-08-25 at 9 41 32 am" src="https://user-images.githubusercontent.com/3680095/29723500-b6352abc-8979-11e7-83d2-39457803bf95.png">

**Comment by brittsikora** [comment]
They also manifest differently in different browsers

Chrome
![controls_bug_chrome](https://user-images.githubusercontent.com/14914918/29981208-d60f123e-8f1a-11e7-9730-5529cc4db6dc.JPG)

IE
![controls_bug_ie](https://user-images.githubusercontent.com/14914918/29981210-d75eb0ea-8f1a-11e7-84a2-feb3b60cf4ed.JPG)

**Comment by samussiah** [comment]
These symbols come from the viz-library data.  Closing this issue.
