### ISSUE TITLE
Throw warnings when non-numeric values are dropped. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#25]
Right now they are being removed without comment here: https://github.com/RhoInc/paneled-outlier-explorer/pull/19/files#diff-f2d1bf62fd73c454622443228f656928R16

**Comment by samussiah** [comment]
Test notes:

- Warning prints to browser console when non-numeric values are removed.

**Comment by samussiah** [comment]
Addressed in v1.
