### ISSUE TITLE
Fix Brushing Bug introduced in `filters` branch

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#26]
<img width="1423" alt="screen shot 2017-08-28 at 4 42 03 pm" src="https://user-images.githubusercontent.com/3680095/29798111-dbc82228-8c0f-11e7-838f-464a59cffb5f.png">

**Comment by samussiah** [comment]
Fixed in ae5d971129d2fb648888561a9926a70210df1d6a commit to #9 / v1 branch.

**Comment by jwildfire** [comment]
Confirmed. Closing.
