### ISSUE TITLE
Allow y-axis range to differ across charts

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#27]
Current settings make many panels impossible to read: 

<img width="849" alt="screen shot 2017-08-28 at 4 45 41 pm" src="https://user-images.githubusercontent.com/3680095/29798185-63f1a25a-8c10-11e7-8d92-bdbc7740b4de.png">

**Comment by jwildfire** [comment]
Using `setting.y.behavior = 'flex'` (shown below) is better at first glance, but I'm guessing you're avoiding it because of weirdness while filtering? I'm thinking that still might be our best option for v1.0. We can always go write a (fairly complex) callback that sets custom domains for each panel later ... 

<img width="784" alt="screen shot 2017-08-28 at 5 27 29 pm" src="https://user-images.githubusercontent.com/3680095/29799135-6c9a31fa-8c16-11e7-9322-b270a16c174e.png">

**Comment by samussiah** [comment]
Yeah, I don't know, good point, forgot about flex.  I do think the y-domain should remain constant when filters change.

Fixed in ae5d971129d2fb648888561a9926a70210df1d6a commit to #9 / v1 branch.
