### ISSUE TITLE
Fix css in controls sidebar

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#28]
Have each option start on a new line:

<img width="280" alt="screen shot 2017-08-28 at 4 43 26 pm" src="https://user-images.githubusercontent.com/3680095/29798266-e083c118-8c10-11e7-8a54-8c69656d3b8b.png">

**Comment by jwildfire** [comment]
I like the idea of having the right justified controls, but i think the right floats are going to keep causing issues. I threw in a quick PR to left-justify instead. If you really want to keep the right justified check marks, we'll probably need to use some kind of rigid table/divs instead of floats.

**Comment by samussiah** [comment]
Test notes:

- Controls don't look stupid.

**Comment by mhickle** [comment]
Pass

![28](https://user-images.githubusercontent.com/31038805/29837015-f240efca-8cc4-11e7-94b8-3cc483109c87.PNG)
