### ISSUE TITLE
Rotate X axis ticks by 45 degrees

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#29]
To avoid overlap like shown: 
<img width="794" alt="screen shot 2017-08-28 at 4 51 53 pm" src="https://user-images.githubusercontent.com/3680095/29798311-3a8c74de-8c11-11e7-8b0b-d62e1ae819af.png">

**Comment by jwildfire** [comment]
See here: https://github.com/RhoInc/safety-outlier-explorer/blob/master/src/onResize.js

**Comment by samussiah** [comment]
Test notes:

- X-axis tick labels do not overlap.
- X-axis tick labels rotate when the `time_cols[].rotate_tick_labels` is set to `true`.
  - Test case: `{"time_cols": [{"value_col": "VISIT", "type": "ordinal", "label": "Visit", "rotate_tick_labels": true, "vertical_space": 100}]}`

**Comment by mhickle** [comment]
Fail 

![29](https://user-images.githubusercontent.com/31038805/29883720-2663d942-8d7f-11e7-992f-f9635d3b12ea.PNG)

**Comment by mhickle** [comment]
Pass

![30](https://user-images.githubusercontent.com/31038805/29887996-4de4e278-8d8d-11e7-8194-4163aaf41669.PNG)
