### ISSUE TITLE
Implement normal ranges.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#3]

**Comment by emmorris** [comment]
Options: show normal range on mouse over of a given person or show layered normal ranges for all selected participants

**Comment by samussiah** [comment]
Test notes:

- Normal range appears on each chart with a nice transparent green hue.
- Normal ranges do not appear if normal range variables do not exist on data file.
  - Test case: `{"lln_col": "fake_lln_var", "uln_col": "fake_uln_var"}`
- Normal range does not affect brushing, i.e. brushing still works within normal range rectangle.

**Comment by mhickle** [comment]
Pass
![3part1](https://user-images.githubusercontent.com/31038805/29835654-aa581098-8cc0-11e7-84cb-ecbdf4f1c446.PNG)
![3part2](https://user-images.githubusercontent.com/31038805/29835663-b01bcc90-8cc0-11e7-9d3d-7621d8e16727.PNG)
