### ISSUE TITLE
Changing x-axis type destroys linked listing 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#30]
<img width="1434" alt="screen shot 2017-08-28 at 5 18 30 pm" src="https://user-images.githubusercontent.com/3680095/29798915-f0c5ae84-8c14-11e7-828d-f0b166f5a843.png">

**Comment by samussiah** [comment]
Test notes:

- Changing x-axis control should not affect listing.

**Comment by mhickle** [comment]
Pass

![30new](https://user-images.githubusercontent.com/31038805/29887984-4057aae6-8d8d-11e7-9906-67cf224ed7b9.PNG)
