### ISSUE TITLE
Implement attached data listing.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#4]

**Comment by samussiah** [comment]
Test notes:

- Data listing displays in its own tab but not on initialization, only when that tab is clicked.
- Data listing displays 25 records per page.
- Data listing pagination contains one link per page up to a maximum of five pages and an ellipsis appears when the data contain more than 125 records.
- Data listing pagination contains single arrows that increase or decrease the displayed page by 1.
- Data listing pagination contains double arrows that display the first or last page when clicked.

**Comment by mhickle** [comment]
Pass 

![4](https://user-images.githubusercontent.com/31038805/29883927-cfb88092-8d7f-11e7-96af-50a4508e9969.PNG)
