### ISSUE TITLE
Images for ReadMe

### ISSUE THREAD

**Issue by mhickle** [RhoInc/paneled-outlier-explorer#46]
![overlay](https://user-images.githubusercontent.com/31038805/30431689-649b02c6-992d-11e7-8497-b4091829652b.gif)

**Comment by mhickle** [comment]
GitHub hack that allows me to use this URL as the permanent image/gif URL in the Markdown file.

**Comment by mhickle** [comment]
![17](https://user-images.githubusercontent.com/31038805/30432338-568c01ba-992f-11e7-8cd4-9b4f43ce6f57.PNG)

**Comment by mhickle** [comment]
![18](https://user-images.githubusercontent.com/31038805/30432477-d19f7e2c-992f-11e7-8d57-9e4bd588541f.PNG)

**Comment by mhickle** [comment]
![gif2](https://user-images.githubusercontent.com/31038805/30434209-a96d443e-9934-11e7-95a9-d2525491bad7.gif)

**Comment by mhickle** [comment]
![23](https://user-images.githubusercontent.com/31038805/30436446-20f9c464-993a-11e7-89b4-d92290850595.PNG)
![24](https://user-images.githubusercontent.com/31038805/30436447-2104acbc-993a-11e7-8296-2387bc785d8c.PNG)

**Comment by mhickle** [comment]
![31](https://user-images.githubusercontent.com/31038805/30436867-39d6d818-993b-11e7-8289-57c9510f54b4.PNG)

**Comment by mhickle** [comment]
![36](https://user-images.githubusercontent.com/31038805/30436966-72dafb62-993b-11e7-9e71-8afde83d5bb0.PNG)

**Comment by jwildfire** [comment]
@mhickle FYI, we can also host the images in the wiki ... might be a slightly better approach for future work.
