### ISSUE TITLE
Aminotransferase (AST) chart is slightly offset from other charts in Internet Explorer

### ISSUE THREAD

**Issue by emmorris** [RhoInc/paneled-outlier-explorer#48]
There is something special about the AST chart that makes it displays slightly offset in Internet Explorer only.  I have unchecked several of the other charts to shift them around and it appears that it has nothing to do with where it is on the page; it seems to be specific to the AST chart.  Please see the image below.

![image](https://user-images.githubusercontent.com/23057086/30616381-0d827ca8-9d60-11e7-8fb1-d2455c82fe4e.png)

**Comment by jwildfire** [comment]
@emmorris Do you have a link to this example? My guess is that the labels is long enough that it is wrapping to the next line, but not sure ...

**Comment by emmorris** [comment]
@jwildfire I was viewing it in https://rhoinc.github.io/CAT/.  I had the following settings:
Version: master
data set: safetyData-queries/ADBDS.csv
Settings: {}

The title text isn't wrapping, but it is possible that there are invisible spaces from it that are wrapping.

**Comment by jwildfire** [comment]
Guessing this is related to #43, so adding to v1.1.

**Comment by brittsikora** [comment]
Will fix in #43
