### ISSUE TITLE
Implement units.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#5]

**Comment by samussiah** [comment]
Test notes:

- Units appear in parentheses on left-hand measure list as well as in chart titles when user specifies an existent unit variable.
  - Test case in CAT: `{"unit_col": "STRESU"}`

**Comment by mhickle** [comment]
Pass

![5](https://user-images.githubusercontent.com/31038805/29836094-1976326a-8cc2-11e7-96e5-23b54a225d95.PNG)
