### ISSUE TITLE
Account for an empty data array or nonexistent normal ranges when drawing normal ranges.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#51]
e.g. in onResize():

```
        if (this.filtered_data.length && this.filtered_data[0][this.config.lln_col] && this.filtered_data[0][this.config.uln_col])
```

# Test notes
* Edit ADBDS.csv so that at least one test has no normal range values.  For example, filter the data on Albumin, delete the normal range values, unfilter the data, and upload it to CAT.  That test should not have a normal range when the _Normal range_ dropdown is set to _LLN-ULN_.
  * Open [CAT](https://rhoinc.github.io/CAT/).
  * Select _safetyData/ADBDS.csv_ in the dataset dropdown.
  * Click the magnifying glass to pull up the data preview.
  * Export the data to CSV.
  * Open the export.
  * Filter to a single TEST.
  * Delete all values in STNRLO and STNRHI, the normal range variables.
  * Remove the filter.
  * Upload the data to CAT by clicking _Choose File_ and then clicking _Load_.  The edited data file should now appear in the data file dropdown.
* Input a bad normal range variable name and verify that the _Normal range_ dropdown does not include _LLN-ULN_.

**Comment by brittsikora** [comment]
Tested with ADBDS-no-normal ranges - pass
