### ISSUE TITLE
Filters not working with Webcharts v1.9.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#58]

**Comment by samussiah** [comment]
Problem arises after brushing charts.

**Comment by jwildfire** [comment]
@samussiah Seems ok using webcharts @`v1.9.0-RC4`. Can you document steps to re-create the bug if you're still getting it?

**Comment by emmorris** [comment]
@samussiah I am seeing the same thing as jwildfire when I look at Paneled Outlier Explorer master in CAT.  Are you still able to reproduce this?
