### ISSUE TITLE
Add toggle for visit type on x-axis

### ISSUE THREAD

**Issue by emmorris** [RhoInc/paneled-outlier-explorer#6]
Study day, visit number, and visit

**Comment by samussiah** [comment]
Test notes:

- Dropdown appears in Controls section with a list of time variable options.
- Charts rerender with corresponding time variable on the x-axis.

**Comment by mhickle** [comment]
Pass
![6part1](https://user-images.githubusercontent.com/31038805/29835920-7694398e-8cc1-11e7-895c-5655962c91be.PNG)
![6part2](https://user-images.githubusercontent.com/31038805/29835925-79b40522-8cc1-11e7-8239-0c882155dc55.PNG)
![6part3](https://user-images.githubusercontent.com/31038805/29835924-79b200e2-8cc1-11e7-99ce-5820c8b59ca5.PNG)
