### ISSUE TITLE
Multiple 'no data found' labels

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#64]
A new label is generated each time the panel is rendered with 0 records. 
<img width="261" alt="screen shot 2017-10-19 at 1 46 16 pm" src="https://user-images.githubusercontent.com/3680095/31793428-fca81696-b4d3-11e7-8a28-bc870817df41.png">

**Comment by jwildfire** [comment]
Fixed in v1.0.3 release

**Comment by jwildfire** [comment]
Test Notes: Filter data down so that a panel has no records in CAT. Confirm that only a single warning is printed in each panel when additional operations are performed.

**Comment by dschwentker** [comment]
Tested and confirmed that, after adding enough filters, I could filter down to get the "No data selected" warning in each panel and that the message was only printed once in each panel in all supported browsers.
