### ISSUE TITLE
Data Listing View in RhoMap

### ISSUE THREAD

**Issue by mhickle** [RhoInc/paneled-outlier-explorer#67]
Currently the data listing appears and functions correctly but leaves this large white space:
![13](https://user-images.githubusercontent.com/31038805/32910395-1869436e-cad7-11e7-9327-0b7685adfb99.PNG)

**Comment by jwildfire** [comment]
Test Notes: Confirm that the listing renders without the whitespace shown above in all major browsers.

**Comment by dschwentker** [comment]
Tested and confirmed that there is no whitespace above the Listing in all supported browsers.
