### ISSUE TITLE
Enable Scroll bar for wide tables

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#68]
Issue was originally: "Highlighted listing displays differently than un-highlighted listing". New title represents reduced scope (as described in comments below).

**Comment by samussiah** [comment]
bug found by @rbudrevich

**Comment by samussiah** [comment]
We need to update the webcharts .css file in RhoMAP to v1.9.

**Comment by samussiah** [comment]
Only thing I changed regarding listing functionality is setting `overflow-x` to `scroll` so the listing doesn't continue off the page.

**Comment by jwildfire** [comment]
Test Notes: Confirm that listing scrolls when it goes past the right hand side of the window.

**Comment by dschwentker** [comment]
Tested and confirmed that there is a scrollbar in the Listing when the data table goes beyond the width of the page in all supported browsers.
