### ISSUE TITLE
In the top right corner of each chart add a maximize button that displays on hover

### ISSUE THREAD

**Issue by emmorris** [RhoInc/paneled-outlier-explorer#7]

**Comment by samussiah** [comment]
Test notes:

- Hovering over a chart displays a "maximize" button that expands chart and draws the chart at the top of the page, scrolling the screen to the expanded chart.
- Hovering over an expanded chart displays a "minimize" button that redraws the chart in its former position.
- Buttons display an appropriate tooltip on hover.

**Comment by mhickle** [comment]
Pass

![7](https://user-images.githubusercontent.com/31038805/29834549-2abee6ca-8cbd-11e7-805c-d4a2fd18ee15.PNG)
