### ISSUE TITLE
Hide visits with no data checkbox

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/paneled-outlier-explorer#73]
Request from Jack - hours and days are smooshing together for a client's version of the PoE and we would like to fix this for him ASAP. Projected deadline is mid-Jan

# Test notes
* A checkbox appears in the _Controls_ section that toggles the display of visits without data.

**Comment by emmorris** [comment]
![image](https://user-images.githubusercontent.com/23057086/34894678-422f5d5e-f7b0-11e7-8b4e-1e7390f95b91.png)
 
Examples from Jack (above is the bad behavior for days 3 and 10; below is the desired behavior)
![image](https://user-images.githubusercontent.com/23057086/34894769-a8e1d86a-f7b0-11e7-8275-99fb6f31aadc.png)
