### ISSUE TITLE
Update settings schema to be compatible with CAT.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/paneled-outlier-explorer#76]

**Comment by emmorris** [comment]
![image](https://user-images.githubusercontent.com/23057086/34996269-17b9f742-faa7-11e7-88e1-918376168cfd.png)
 Here is what the chart looks like when you attempt to load it with the current settings.  

It works right now if you just put in '{}' as the setting.

**Comment by jwildfire** [comment]
Working well now. Closing
