### ISSUE TITLE
Make the "x" button only show on hover

### ISSUE THREAD

**Issue by emmorris** [RhoInc/paneled-outlier-explorer#8]

**Comment by samussiah** [comment]
Test notes:

- Charts display a "close" button on hover.
- Clicking "close" button removes chart and un-checks associated checkbox.

**Comment by mhickle** [comment]
Pass
![8](https://user-images.githubusercontent.com/31038805/29836179-70b91042-8cc2-11e7-92c9-a91bef575019.PNG)
