### ISSUE TITLE
Allow users to define custom normal ranges

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/paneled-outlier-explorer#93]
Create control with 4 options for normal ranges: 
- data-driven  - default if available. hidden if no normal ranges are given in the data. 
- SD - default if data-driven isn't available. When selected user is given a numeric input to specify the number of SDs from the mean. Default = 2.
- Quantiles - when selected the user is give 2 inputs to provide upper and lower quantiles (range: 0 - 1.0, default [0.05, 0.95]
- Normal - when selected the user is give 2 inputs to provide upper and lower limits. default [min - max]
  - Leaving out for now because this one'd have to be measure-specific.  Perhaps in the future the normal range could be draggable...

# Test notes
* A dropdown labeled _Normal range method_ appears in the controls section with three or four options:
  * _None_
  * _LLN-ULN_ - provided the data contain limit of normal variables
  * _Standard Deviation_
  * _Quantiles_
* Selecting _Standard Deviation_ displays a text input labeled _Number of standard deviations_ and defaults to 1.96.
* Selecting _Quantiles_ displays two text inputs, one for the lower quantile and one for the upper quantile, labeled _Lower quantile_ and _Upper quantile_ respectively, that default to .05 and .95.

**Comment by jwildfire** [comment]
@samussiah are the limits for the the data driven inliers added in 1.1 calculated for each participant, or just once per measure?

**Comment by samussiah** [comment]
The outliers are calculated per result and an additional participant-level flag is derived if that participant has at least one outlier.

The normal ranges are now reflect the limits of normal, given the normal range method.  The data-driven normal range displays the median LLN/ULN.
